window.blinkPortfolioProjects = [
  {
    id: "crazy-doctor",
    title: "Crazy Doctor",
    category: "منصة تعليمية",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    summary: "منصة تدريب ومحتوى تعليمي منظمة بهيكل دروس ووحدات ولوحة طالب وتجربة تعلم سلسة.",
    details:
      "قمنا ببناء تجربة تعليمية مرتبة لعرض البرامج، الدروس، والوحدات بطريقة تساعد على الوصول السريع للمحتوى وتدعم قرار الاشتراك والمتابعة.",
    deliverables: ["هيكلة منصة تعليمية واضحة", "تحسين تجربة الطالب", "تنظيم المحتوى والصفحات"],
    projectUrl: "https://crazy-doctor.com/",
    homeFeatured: true,
  },
  {
    id: "waslny",
    title: "Waslny",
    category: "منصة توصيل",
    image: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=900&q=80",
    summary: "منصة خدمية لتسهيل طلبات التوصيل مع واجهة خفيفة وتنقل واضح وتجربة mobile-first.",
    details:
      "رتبنا تجربة الحجز والطلب لتكون سريعة على الهاتف، مع عرض واضح للخدمة ونقاط التفاعل الأساسية بما يدعم الاستخدام المتكرر.",
    deliverables: ["واجهة خدمية سريعة", "تجربة مناسبة للهاتف", "تقوية مسار الطلب"],
    projectUrl: "https://waslny.app/",
    homeFeatured: true,
  },
  {
    id: "koko-sons",
    title: "Koko & Sons Online",
    category: "متجر إلكتروني",
    image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=900&q=80",
    summary: "متجر حديث بعرض منتجات منظم وتجربة تصفح سهلة مع صفحات تدعم التحويل والشراء.",
    details:
      "نفذنا تجربة متجر واضحة للمنتجات والفئات مع صفحات بيع منظمة وترتيب محتوى يسهّل اتخاذ قرار الشراء ويقوي الثقة.",
    deliverables: ["تصميم متجر WooCommerce", "تنظيم الفئات والمنتجات", "صفحات تدعم التحويل"],
    projectUrl: "https://kokoandsonline.com/",
    homeFeatured: true,
  },
  {
    id: "el-volt",
    title: "El-Volt",
    category: "موقع شركة",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    summary: "موقع تعريفي احترافي لعرض خدمات الشركة وهوية العلامة التجارية بشكل منظم وواضح.",
    details:
      "طورنا صفحة شركة تبرز الخدمات والقدرات التنفيذية بصورة مؤسسية، مع توزيع بصري مريح ورسائل أوضح للزائر.",
    deliverables: ["هوية مؤسسية داخل الموقع", "عرض خدمات منظم", "تحسين وضوح الرسالة"],
    projectUrl: "https://el-volt.com/",
  },
  {
    id: "sruh-law-firm",
    title: "Sruh Al Wthaq Law Firm",
    category: "موقع قانوني",
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80",
    summary: "موقع قانوني يعكس الثقة والحضور المؤسسي مع تقسيم خدمات واضح ونبرة رسمية قوية.",
    details:
      "هيكلنا الموقع القانوني بطريقة تعطي انطباعًا مهنيًا قويًا مع إبراز مجالات العمل ومسارات التواصل والاستفسار بصورة أكثر ثقة.",
    deliverables: ["واجهة قانونية رسمية", "تقسيم خدمات واضح", "دعم الثقة والاعتمادية"],
    projectUrl: "https://sruhalwthaq-lawfirm.sa/",
  },
  {
    id: "wasl-altamayoz",
    title: "Wasl Al Tamayoz",
    category: "متجر إلكتروني",
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=900&q=80",
    summary: "متجر إلكتروني بعرض فئات وعروض وتجربة شراء مبسطة ومهيأة للأجهزة المختلفة.",
    details:
      "نظمنا واجهة المتجر والفئات والعروض ليظهر المشروع بصورة أوضح ويقود الزائر إلى سلة الشراء بخطوات مختصرة.",
    deliverables: ["عرض فئات وعروض", "تنظيم رحلة الشراء", "توافق كامل مع الهاتف"],
    projectUrl: "https://wasl-altamayoz.com/",
  },
  {
    id: "design-sense",
    title: "Design Sense",
    category: "أثاث ومتاجر",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    summary: "متجر أثاث بتركيز بصري قوي على عرض المنتجات مع شبكة مرتبة وتجربة حديثة.",
    details:
      "بنينًا واجهة تركّز على الصورة والمنتج وتفاصيله مع ترتيب عرض يساعد على إبراز القطع ورفع جودة الانطباع العام.",
    deliverables: ["تصميم بصري للمنتجات", "شبكة عرض مرتبة", "تقوية إبراز الهوية"],
    projectUrl: "https://designsens.com/",
  },
  {
    id: "abo-alward-phone",
    title: "Abo Alward Phone",
    category: "إلكترونيات",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    summary: "موقع تجاري لعرض منتجات وخدمات إلكترونية بواجهة بسيطة وصفحات سريعة التحميل.",
    details:
      "ركزنا على السرعة ووضوح عرض الأجهزة والخدمات، مع واجهة عملية تناسب المتاجر التي تحتاج عرضًا مباشرًا وواضحًا.",
    deliverables: ["عرض منتجات إلكترونية", "صفحات خفيفة وسريعة", "واجهة عملية واضحة"],
    projectUrl: "https://aboalwardphone.com/",
  },
  {
    id: "namaa-vision",
    title: "Namaa Vision",
    category: "هوية مؤسسية",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
    summary: "موقع شركة يدعم الحضور الرقمي ويعرض الهوية والخدمات بشكل نظيف ومنظم.",
    details:
      "قدمنا صفحة شركة موجهة لإبراز الهوية والخدمات ورفع الوضوح المؤسسي أمام الزوار والشركاء المحتملين.",
    deliverables: ["عرض هوية الشركة", "صفحات خدمات مرتبة", "تحسين الحضور الرقمي"],
    projectUrl: "https://namaavision.com/",
  },
  {
    id: "rock-frontiers",
    title: "Rock Frontiers",
    category: "شركة وعلامة",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80",
    summary: "موقع شركة يعرض الخدمات ويقوي الظهور الرقمي بهيكل عصري واستجابة ممتازة.",
    details:
      "أعدنا تنظيم العرض الرقمي للشركة بصورة أكثر عصرية وهدوءًا مع محتوى أوضح ومساحة أفضل لبناء الثقة.",
    deliverables: ["هيكل عصري للموقع", "عرض قدرات الشركة", "استجابة ممتازة على الأجهزة"],
    projectUrl: "https://rockfrontiers.com/",
  },
  {
    id: "marzouk-legal",
    title: "Marzouk Legal Translation",
    category: "ترجمة قانونية",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    summary: "موقع متخصص في خدمات الترجمة القانونية مع عرض خدمات مباشر وترتيب مريح للمستخدم.",
    details:
      "صممنا عرضًا مهنيًا للخدمات القانونية والترجمة المعتمدة مع محتوى مباشر ومسارات تواصل واضحة.",
    deliverables: ["عرض خدمات متخصصة", "تقوية الثقة القانونية", "تنظيم المحتوى والخدمات"],
    projectUrl: "https://marzouk-lgltrans.com/",
  },
  {
    id: "proofapoxy",
    title: "Proofapoxy",
    category: "خدمات صناعية",
    image: "https://images.unsplash.com/photo-1581092335397-9583eb92d232?auto=format&fit=crop&w=900&q=80",
    summary: "موقع خدمات صناعية لعرض حلول الأرضيات والعزل والطلاءات بشكل مهني وواضح.",
    details:
      "هيكلنا المحتوى الصناعي بطريقة تسهّل فهم الخدمات والمواد والحلول، مع واجهة تخاطب العملاء المهنيين بوضوح.",
    deliverables: ["عرض حلول صناعية", "تنظيم خدمات ومواد", "تجربة واضحة للعميل المهني"],
    projectUrl: "https://proofapoxy.com/",
  },
  {
    id: "sharp-edge-tools",
    title: "Sharp Edge Tools",
    category: "معدات وأدوات",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80",
    summary: "موقع منتجات وأدوات صناعية بتنظيم واضح للفئات والمنتجات مع واجهة عملية.",
    details:
      "قدمنا تجربة عرض منظمة للفئات والمنتجات الصناعية مع واجهة تسهّل الاستكشاف والوصول السريع للأدوات المطلوبة.",
    deliverables: ["تنظيم الفئات الصناعية", "عرض منتجات واضح", "واجهة عملية وسريعة"],
    projectUrl: "https://sharpedge-tools.com/",
  },
  {
    id: "hadreen-center",
    title: "Hadreen Center",
    category: "تعليم وجمال",
    image: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80",
    summary: "موقع يعرض خدمات مركز متخصص بطريقة واضحة مع تنظيم الواجهة ومسارات الحجز والاستفسار.",
    details:
      "اعتمدنا على تقديم الخدمة والبرامج بشكل مرتب مع إبراز الثقة وسهولة الوصول إلى معلومات التواصل والقرارات المهمة.",
    deliverables: ["ترتيب الخدمات والبرامج", "تحسين مسارات الحجز", "واجهة أوضح للمركز"],
    projectUrl: "https://hadreencenter.com/",
    homeFeatured: true,
    source: "yousefmo",
  },
  {
    id: "social-media-care",
    title: "Social Media Care",
    category: "خدمات رقمية",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
    summary: "واجهة خدمية لعرض خدمات الإدارة الرقمية والسوشيال ميديا بصورة حديثة ومقنعة.",
    details:
      "تم ترتيب عرض الخدمات الرقمية والباقات ورسائل القيمة بطريقة تساعد على توضيح الفائدة وبدء التواصل بسرعة.",
    deliverables: ["عرض خدمات رقمية", "رسائل بيع أوضح", "تجربة تواصل أسرع"],
    projectUrl: "https://socialmediacare.ae",
    homeFeatured: true,
    source: "yousefmo",
  },
  {
    id: "almouwafak-rent-car",
    title: "Al Mouwafak Rent Car",
    category: "تأجير سيارات",
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80",
    summary: "موقع لتأجير السيارات يبرز الأسطول والخدمات والعروض بطريقة سهلة للمقارنة والاختيار.",
    details:
      "تم تحسين طريقة عرض السيارات والخدمات ووسائل الحجز بما يسهّل على الزائر فهم الخيارات واتخاذ القرار سريعًا.",
    deliverables: ["عرض أسطول السيارات", "تحسين الحجز والاستفسار", "تقوية الواجهة البيعية"],
    projectUrl: "https://www.almouwafakrentcar.com",
    source: "yousefmo",
  },
  {
    id: "nujom-almouwafak",
    title: "Nujom Al Mouwafak",
    category: "عقارات وخدمات",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=80",
    summary: "موقع يقدم خدمات عقارية وتجارية بواجهة نظيفة ورسائل واضحة وهوية أكثر فخامة.",
    details:
      "عالجنا طريقة عرض المشاريع والخدمات والعناصر التعريفية لتبدو أكثر مهنية وتدعم قرار التواصل والاستفسار.",
    deliverables: ["تنظيم عرض الخدمات", "إبراز الهوية", "تحسين تجربة التصفح"],
    projectUrl: "https://www.nujomalmouwafak.com",
    source: "yousefmo",
  },
  {
    id: "farm555",
    title: "Farm 555",
    category: "موقع أعمال",
    image: "https://yousefmo.com/images/farm555.png",
    summary: "موقع أعمال زراعية يعرض الخدمات والمنتجات بطريقة حديثة مع هوية بصرية قوية.",
    details:
      "يبرز هذا المشروع طريقة تقديم الخدمات والمنتجات في واجهة عصرية مع توزيع بصري مريح ومحتوى يشرح النشاط بوضوح.",
    deliverables: ["تصميم أعمال حديث", "عرض خدمات ومنتجات", "تقوية الثقة والانطباع الأول"],
    projectUrl: "https://farm555.com",
    homeFeatured: true,
    source: "yousefmo",
  },
  {
    id: "accounting-taxation",
    title: "Accounting & Taxation",
    category: "خدمات مالية",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80",
    summary: "مشروع يعرض خدمات المحاسبة والضرائب بأسلوب مهني يساعد على توضيح الخدمة وبناء الثقة.",
    details:
      "أضفناه ضمن سابقة الأعمال المستخلصة من معرض Yousefmo، ويعكس خبرة في تقديم الخدمات المهنية بلغة واضحة وهيكل منظم.",
    deliverables: ["عرض خدمات مهنية", "تقوية الثقة المؤسسية", "تنظيم المحتوى المالي"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
  {
    id: "events-planning",
    title: "Events Planning",
    category: "تنظيم فعاليات",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80",
    summary: "واجهة موجهة لخدمات تنظيم الفعاليات مع إبراز الأعمال والخدمات بصورة أكثر حيوية وتنظيمًا.",
    details:
      "يعكس المشروع القدرة على بناء واجهات خدمية موجهة للفعاليات تتوازن بين الهوية البصرية وسهولة عرض الخدمات.",
    deliverables: ["واجهة بصرية للفعاليات", "عرض خدمات منظم", "ترتيب أقسام العمل"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
  {
    id: "government-transactions",
    title: "Government Transactions",
    category: "معاملات حكومية",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    summary: "تجربة عرض لخدمات المعاملات الحكومية مع تقسيم واضح للطلبات والخدمات ومسارات التواصل.",
    details:
      "المشروع يوضح أسلوبنا في تبسيط الخدمات الإجرائية داخل واجهة تبدو رسمية وواضحة للمستخدم النهائي.",
    deliverables: ["تقسيم خدمات واضح", "واجهة رسمية مريحة", "ترتيب مسارات التواصل"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
  {
    id: "legal-services-yousef",
    title: "Legal Services",
    category: "استشارات قانونية",
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80",
    summary: "مشروع قانوني يعرض الخدمات والمجالات القانونية بصورة تبني الثقة وتدعم الحضور المؤسسي.",
    details:
      "تم إدراج هذا العمل من معرض Yousefmo لتمثيل الخبرات القانونية المعروضة هناك ضمن سابقة الأعمال الموحدة.",
    deliverables: ["هيكل قانوني واضح", "تقوية الثقة المؤسسية", "عرض مجالات العمل"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
  {
    id: "real-estate-yousef",
    title: "Real Estate",
    category: "عقارات",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=80",
    summary: "واجهة عقارية لعرض الخدمات أو المشاريع مع تنظيم واضح للعناصر والرسائل الأساسية.",
    details:
      "يُظهر المشروع قدرة التنفيذ في القطاعات العقارية من خلال عرض مرتب للمحتوى والخدمات ومساحات الثقة.",
    deliverables: ["عرض عقاري منظم", "بناء انطباع أقوى", "تحسين وضوح المحتوى"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
  {
    id: "retail-services-yousef",
    title: "Retail & Services",
    category: "تجزئة وخدمات",
    image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=900&q=80",
    summary: "نماذج أعمال تجمع بين التجزئة والخدمات مع واجهات تركز على البيع ووضوح القيمة.",
    details:
      "أدرجنا هذا العمل ضمن البورتفوليو الموحد لأنه يمثل نمطًا مهمًا من المشاريع المذكورة داخل Yousefmo.",
    deliverables: ["هيكلة بيع أوضح", "عرض خدمات ومنتجات", "تحسين التحويل"],
    projectUrl: "https://yousefmo.com/#projects",
    source: "yousefmo",
  },
];
